name: "TelesalesCoach's Dokploy Deploy Action"
description: "Deploy an application to Dokploy"
author: "Pukimaa"
inputs:
    APPLICATION_ID:
        description: "The name of the application to deploy"
        required: true
    DOKPLOY_HOST:
        description: "The host of the Dokploy instance"
        required: true
    DOKPLOY_TOKEN:
        description: "The token to authenticate with Dokploy"
        required: true
    
runs:
    using: "composite"
    steps:
      - name: Deploy to Dokploy
        shell: bash
        run: |
          curl -X 'POST' \
            'https://${{ inputs.DOKPLOY_HOST }}/api/application.deploy' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'x-api-key: ${{ inputs.DOKPLOY_TOKEN }}' \
            -d '{
              "applicationId": "${{ inputs.APPLICATION_ID }}"
          }'

branding:
  icon: "box"
  color: "gray-dark"
