name: "Dokploy Deploy Action"
description: "Deploy an application to Dokploy"
author: "jmischler72"
inputs:
    application_name:
        description: "The name of the application to deploy"
        required: true
        default: "server"
    project_name:
        description: "The name of the project to deploy"
        required: true
        default: "tetrarena"
branding:
  icon: "tool"
  color: "gray-dark"