name: Dokploy Deploy

on:         
  workflow_call:
    secrets:
      DOKPLOY_HOST:
        required: true  
      DOKPLOY_TOKEN:
        required: true  
      APPLICATION_ID:
        required: true  
        
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Dokploy
              run: |
                curl -X 'POST' \
                  'https://${{ secrets.DOKPLOY_HOST }}/api/application.deploy' \
                  -H 'accept: application/json' \
                  -H 'Content-Type: application/json' \
                  -H "Authorization: Bearer ${{ secrets.DOKPLOY_TOKEN }}" \
                  -d '{
                  "applicationId": "${{ secrets.APPLICATION_ID }}"
                }'