name: Dokploy Deploy

on:         
  workflow_call:
    secrets:
      DOKPLOY_HOST:
        required: true  
      DOKPLOY_TOKEN:
        required: true  
      APPLICATION_ID:
        required: true  
        
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Dokploy
              env:
                DOKPLOY_HOST: ${{ secrets.DOKPLOY_HOST }}
                DOKPLOY_TOKEN: ${{ secrets.DOKPLOY_TOKEN }}
                APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
              run: |
                curl -X 'POST' \
                  'https://$DOKPLOY_HOST/api/application.deploy' \
                  -H 'accept: application/json' \
                  -H 'Content-Type: application/json' \
                  -H "Authorization: Bearer $DOKPLOY_TOKEN" \
                  -d '{
                  "applicationId": "'$APPLICATION_ID'"
                }'